name: CI Tests Only

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    
    - name: Run linting
      run: |
        pip install black isort flake8
        black --check app/ || true
        isort --check-only app/ || true
        flake8 app/ --max-line-length=120 || true
    
    - name: Run tests
      env:
        SECRET_KEY: test-secret-key
        DATABASE_URL: "sqlite+aiosqlite:///:memory:"
        TESTING: "true"
      run: |
        pytest tests/ --cov=app --cov-report=xml
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false